[options.textual]
mainfont = "Tex Gyre Heros"
mathfont = "Latin Modern Math"
left =   "3cm"
top =    "3cm"
right =  "2cm"
bottom = "2cm"

[hyper.setup]
colorlinks = "true"
linkcolor = "black"
urlcolor = "black"
citecolor = "black"
pdfhighlight = "/N"

[bibliography]
style = "abnt-numeric"