[data]
title = "Título da Dissertação/tese"
author = "Timóteo Fassoni"
date = "Fevereiro/2026"
address = "Viçosa, Minas Gerais"

[[advisor]]
name = "Silvio Ferreira"
affiliation = "UFV"
role = "Orientador"

[[advisor]]
name = "Wesley Cota"
affiliation = "UFV"
role = "Coorientador"

[metadata]
type = "Dissertação"
degree = "Mestre em Física"
graduate = "Física"
university = "Universidade Federal de Viçosa"
affiliation = "UFV"
center = "Centro de Ciências Exatas"
program = "Programa de Pós-Graduação em Física"
edital = ""

[[board]]
name = "Ciclana da Silva"
affiliation = "USP"
title = "Profa. Dra."
role = "Membro Titular"

[[board]]
name = "Beltrano de Souza"
affiliation = "UFV"
title = "Prof. Dr."
role = "Membro Suplente"

[frontmatter]
titlepage = true
coverpage = true
approvalpage = true
assentpage = true
dedication = true
acknowledgments = true
epigraph = true
abstract.native = true
abstract.foreign = true
listof.figures = false
listof.tables = false
listof.acronym = false
listof.symbols = false
toc = true # (Table of Contents)

[abstract]
native.name = "Resumo"
native.keyword = "Palavra-chave"
native.keywords = ["Palavra-chave 1", "Palavra-chave 2", "Palavra-chave 3"]
foreign.name = "Abstract"
foreign.keywords = ["Keyword 1", "Keyword 2", "Keyword 3"]
foreign.keyword = "Keyword"

[options.global]
babel = "brazilian"
papersize = "a4paper"

[bibliography]
file = "bib/ref.bib"