[options.textual]
mainfont = "TeX Gyre Pagella"
mathfont = "TeX Gyre Pagella Math"
left =   "2.5cm"
top =    "2.5cm"
right =  "2.5cm"
bottom = "2.5cm"

[hyper.setup]
colorlinks = "true"
linkcolor = "blue"
urlcolor = "blue"
citecolor = "blue"
pdfhighlight = "/N"

[bibliography]
style = "numeric-comp"